site_name: "HRProcess: Manual del usuario WF Vacaciones"

nav:
  - Primeros pasos: index.md
  - Funciones Usuarios: funcionesUsuarios.md
  - Funciones Aprobadores: funcionesAprobadores.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra:
  generator: false


theme:
  features:
    - navigation.instant
    - navigation.footer
    - navigation.path
    - toc.integrate
    - navigation.top
    - navigation.expand

  language: es
  font:
    text: Noto Sans
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


#  palette:
#    scheme: slate
#    primary: black
#    accent: blue

  custom_dir: overrides

  logo: logoHRprocess.v1.png